# Generated by Django 3.2.9 on 2020-01-01 00:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LumiereCite', '0002_auto_20211130_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillanDeLumiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('etablissements', models.CharField(max_length=100)),
                ('enseignant', models.CharField(max_length=100)),
                ('numbre_de_fille', models.CharField(max_length=100)),
                ('numbre_de_garcon', models.CharField(max_length=100)),
                ('rapports_suggestions', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('add_date', models.DateField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
