# Generated by Django 3.2.4 on 2021-11-18 15:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfantsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('date_de_naissance', models.DateField(max_length=150)),
                ('lieu_de_naissance', models.CharField(max_length=150)),
                ('residence', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('groupe', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('classe', models.CharField(max_length=150)),
                ('sexe', models.CharField(max_length=150)),
                ('distance_maison_district', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_maison_ecole', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_des_parents_ou_tuteurs', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=150, null=True)),
                ('description_sur_l_enfant', ckeditor.fields.RichTextField()),
                ('enfant_images', models.ImageField(blank=True, null=True, upload_to='images/enfant')),
                ('add_date', models.DateField(auto_now_add=True, max_length=150)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
