# Generated by Django 3.2.4 on 2021-11-30 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Supports', '0002_region_reponses'),
        ('Enfants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfantspost',
            name='avec_qui_vit_il',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='groupe_sanguin',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='les_freres_sont_ils_dans_leglise',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='les_parents_sont_ils_dans_leglise',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='les_soeurs_sont_elles_dans_leglise',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='nom_des_freres',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='nom_des_parentes',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='nom_des_soeurs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='nombre_de_freres',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='nombre_de_soeurs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='rhesus',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='role_dans_leglise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Supports.roles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfantspost',
            name='talents_de_l_enfant',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
